language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t r4pt0s/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true r4pt0s/docker-react npm run test 

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API
  app: docker-react-travis
  on:
    branch: master
